const express = require("express");
const PDFDocument = require("pdfkit");
const QRCode = require("qrcode");
const fs = require("fs");
const path = require("path");
const cloudinary = require("../config/cloudinary");
const NOC = require("../models/NOC");
const Application = require("../models/Application");

const router = express.Router();

//ensure temp directory exists
const tempDir = path.join(__dirname, "../temp");
if (!fs.existsSync(tempDir)) {
    fs.mkdirSync(tempDir);
}


router.post("/generate-noc/:id", async (req, res) => {
    try {
        const { id } = req.params;

        
        const existingNOC = await NOC.findOne({ applicationId: id });
        if (existingNOC) {
            return res.status(200).json({
                message: "NOC already generated.",
                nocUrl: existingNOC.nocUrl
            });
        }


        const application = await Application.findById(id);
        if (!application || application.status !== "Approved") {
            return res.status(404).json({ message: "Approved application not found" });
        }


        const qrPath = path.join(tempDir, `qrcode_${id}.png`);
        const qrData = `Application ID: ${application._id}\nOwner Name: ${application.ownerName}\nBusinessName Name: ${application.businessName}\nStatus: Approved`;
        await QRCode.toFile(qrPath, qrData);

        const pdfPath = path.join(tempDir, `NOC_${id}.pdf`);
        const doc = new PDFDocument();
        const stream = fs.createWriteStream(pdfPath);
        doc.pipe(stream);


        doc.fontSize(20).text("FIRE SAFETY NOC CERTIFICATE", { align: "center" });
        doc.moveDown(0.5);
        doc.fontSize(16).text("GOVERNMENT OF INDIA", { align: "center" });
        doc.moveDown(1);

        const logoPath = path.join(__dirname, "../assets/govt_logo.png");
        doc.image(logoPath, { width: 80, align: "center" });
        doc.moveDown(5);

        doc.fontSize(12).text(`Application ID: ${application._id}`, { align: "left" });
        doc.text(`Owner Name: ${application.ownerName}`);
        doc.text(`Business Name: ${application.businessName}`);
        doc.text(`Email: ${application.email}`);
        doc.text(`Contact: ${application.contact}`);
        doc.text(`Address: ${application.address}`);
        doc.moveDown(1);


        doc.text(`Issued On: ${new Date().toLocaleDateString()}`);
        const expiryDate = new Date();
        expiryDate.setFullYear(expiryDate.getFullYear() + 3);
        doc.text(`Expiry Date: ${expiryDate.toLocaleDateString()}`);
        doc.moveDown(1);

        doc.text(
            `This is AI generated Risk Score (so this subject is not generated by human, it might be false): ${application.riskScore}`
        );
        doc.moveDown(1);

        // Legal Notice
        doc.text("This is a digitally generated NOC certificate and is valid for legal purposes.", {
            align: "center",
        });
        doc.moveDown(1);

        doc.image(qrPath, { width: 100, align: "center" });

        doc.end();

        stream.on("finish", async () => {
            console.log(`PDF Generated: ${pdfPath}`);


            const cloudResult = await cloudinary.uploader.upload(pdfPath, {
                resource_type: "raw",
                format: "pdf",
                public_id: `NOC_${id}`
            });

            console.log("Cloudinary Upload Response:", cloudResult);


            const noc = new NOC({
                applicationId: application._id,
                ownerName: application.ownerName,
                businessName: application.businessName,
                email: application.email,
                contact: application.contact,
                nocUrl: cloudResult.secure_url,
                issuedOn: new Date(),
            });
            await noc.save();

            res.status(200).json({
                message: "NOC generated and uploaded successfully",
                nocUrl: cloudResult.secure_url
            });
        });

    } catch (error) {
        console.error("Error generating NOC:", error);
        res.status(500).json({ message: "Error generating NOC", error });
    }
});


router.get("/status/:id", async (req, res) => {
    try {
        const { id } = req.params;
        const noc = await NOC.findOne({ applicationId: id });

        if (noc) {
            return res.status(200).json({ nocUrl: noc.nocUrl, issuedOn: noc.issuedOn });
        } else {
            return res.status(200).json({ nocUrl: null });
        }
    } catch (error) {
        console.error("Error checking NOC status:", error);
        res.status(500).json({ message: "Error checking NOC status" });
    }
});

router.get("/user/nocs", async (req, res) => {
    try {
        const { email } = req.query; 

        if (!email) {
            return res.status(400).json({ message: "Email is required" });
        }

        const nocs = await NOC.find({ email });

        if (!nocs.length) {
            return res.status(404).json({ message: "No NOCs found for this user." });
        }

        res.status(200).json(nocs);
    } catch (error) {
        console.error("❌ Error fetching NOCs:", error);
        res.status(500).json({ message: "Error fetching NOCs", error });
    }
});

module.exports = router;
